name: ID PASS - MOSIP Resident Application
  
on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # cache npm dependencies for faster builds
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: Install npm dependencies
        run: |
          npm ci
      - name: Build App Newlogic Release
        run: |
          cd android
          [ ! -z "$FIREBASE_SECRET" ] && gpg -o app/google-services.json --batch --passphrase="$FIREBASE_SECRET" -d app/google-services.json.gpg || echo "FIREBASE_SECRET not defined"
          ./gradlew :app:assembleNewlogicRelease
        env:
          BACKEND_SERVICE_URL: https://qa-triple-rc2.mosip.net/residentmobileapp
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: android/app/build/outputs/apk/newlogic/release/
          retention-days: 1
