name: ID PASS - MOSIP Resident Application Custom build

env:
  backendServiceDefaultUrl: https://resident-app.newlogic.dev

on:
  workflow_dispatch:
    inputs:
      backendServiceUrl:
        description: 'Backend service URL'
        required: true
        default: 'https://resident-app.newlogic.dev'
        type: choice
        options:
        - https://resident-app.newlogic.dev
        - http://local.newlogic.dev
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build App Newlogic Release
        run: |
          cd android && ./gradlew :app:assembleNewlogicRelease
        env:
          BACKEND_SERVICE_URL: ${{ github.event.inputs.backendServiceUrl }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: android/app/build/outputs/apk/newlogic/release/
          retention-days: 1
