name: PR - IOS build verification

on:
  push:
    branches:
      - main
      - develop
      - demobranch
      - qa-develop
      - 0.9
    tags:
      - '*'
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - develop
      - 'release-**'
    tags:
      - '*'

jobs:
  build_ios:
    name: Building the IPA
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install npm dependencies
        run: |
          npm install

      - name: Install Pod
        run: |
          cd ios
          pod install

      - name: Building the IPA
        run: |
          cd ios
          fastlane build_app_for_automation_on_simulator
